## Colors configuration
colors:
  # Default colors
  primary:
    background: '#102032'
    foreground: '#FFFFFF'

  # Normal colors
  normal:
    black:   '#3B4252'
    red:     '#BF616A'
    green:   '#A3BE8C'
    yellow:  '#C2104F'
    blue:    '#81A1C1'
    magenta: '#B48EAD'
    cyan:    '#88C0D0'
    white:   '#E5E9F0'

  # Bright colors
  bright:
    black:   '#4C566A'
    red:     '#BF616A'
    green:   '#A3BE8C'
    yellow:  '#EBCB8B'
    blue:    '#81A1C1'
    magenta: '#B48EAD'
    cyan:    '#8FBCBB'
    white:   '#ECEFF4'